env: "local" # local, dev, prod

httpServer:
  addr: "0.0.0.0:6000"
  readTimeout: 5s
  writeTimeout: 5s
  idleTimeout: 60s

dbPostgres:
  host: "0.0.0.0"
  port: 5433
  user: "auth"
  password: "auth"
  db: "users"
  poolMaxConn: 10
